In [1]:
import sys,pysam, time,os,re,copy,argparse, tensorboard,gzip
from collections import Counter
import pandas as pd
import numpy as np
import multiprocessing as mp
from pysam import VariantFile
import tensorflow as tf
import generate_pileups as gcp
from matplotlib import pyplot as plt
from importlib import reload
import CNN_model as model
import utils


In [72]:
sam_hg001_ulr_path='/home/ahsanm1/umair_wlab/data/NA12878_nanopore_rel5/rel5-guppy-0.3.0-chunk10k.sorted.bam'
fasta_path='/home/ahsanm1/umair_wlab/data/NA12878_nanopore_rel5/GRCh38_full_analysis_set_plus_decoy_hla.fa'
vcf_path='/home/ahsanm1/umair_wlab/data/NanoVar_data/HG001.inbed.SNPonly.uniq.normalizeGT.vcf.gz'
sam_path='/home/ahsanm1/shared_data/NA12878/Nanopore/Alignmentsbychromosome/chr20.sorted.bam'
sam_hg001_ulr = pysam.Samfile(sam_path, "rb")
amplicon_path='/home/ahsanm1/umair_wlab/data/CYP2D6/CYP2D6.bam'

params={'mode':'testing','threshold':0.15,'chrom':'chr20','start':25300892,'end':27420892,'sam_path':sam_path,'fasta_path':fasta_path,'vcf_path':vcf_path,'depth':32,'window':16,'cpu':8}

In [38]:
dct={'mode':'testing','threshold':0.15,'chrom':'chr20','start':45300892,'end':47420892,'sam_path':sam_hg001_ulr_path,'fasta_path':fasta_path,'vcf_path':vcf_path,'depth':32,'window':16,'cpu':8}


In [39]:
params={'mode':'testing','threshold':0.15,'chrom':'chr20','start':45300892,'end':47420892,'sam_path':sam_hg001_ulr_path,'fasta_path':fasta_path,'vcf_path':vcf_path,'depth':32,'window':16,'cpu':8}
res2=gcp.get_candidates(params)
len(res2)

40468

In [40]:
params={'mode':'testing','threshold':0.15,'chrom':'chr20','start':45300892,'end':47420892,'sam_path':sam_path,'fasta_path':fasta_path,'vcf_path':vcf_path,'depth':32,'window':16,'cpu':8}
res=gcp.get_candidates(params)
len(res)

40468

In [41]:
tr=extract_vcf(params)

In [91]:
amp_params={'mode':'testing','threshold':0.15,'bed':False,'chrom':'chr22','start':42522077,'end':42527144,'sam_path':amplicon_path,'out_path':'/home/ahsanm1/umair_wlab/data/CYP2D6/','fasta_path':fasta_path,'vcf_path':vcf_path,'depth':1024,'window':16,'cpu':8}

In [92]:
reload(gcp)
gcp.generate(amp_params)


starting pileups
starting pool:42522077


ValueError: operands could not be broadcast together with shapes (17,32) (17,33) 

In [79]:
amp_file =pysam.Samfile(amplicon_path, "rb")

In [81]:
r_list=[]
for pcol in amp_file.pileup('chr22',42522077,42527144,min_base_quality=0,flag_filter=0x4|0x100|0x200|0x400,truncate=True):
    s=''
    for pread in pcol.pileups:
            if type(pread.query_position)==int:
                s+=pread.alignment.query_sequence[pread.query_position]
            else:
                s+='*'
    #s=''.join([pread.alignment.query_sequence[pread.query_position] if pread.query_position else '*' for pread in pcol.pileups if not pread.alignment.flag & (0x4|0x100|0x200|0x400|0x800)])
    #print(s)
    seq=''
    for x in pcol.get_query_sequences():
        if x in ['N','n']:
            print('NNNN')
        elif x not in ['N','n']:
            if len(x)>0:
                seq+=x.upper()
            else:
                seq+='*'
        r_list.append(seq)
    
    

In [82]:
len(r_list)

6012573

In [44]:
v_pos=27522077
for pcol in samfile.pileup('chr20',v_pos-1,v_pos,min_base_quality=0,stepper='nofilter',truncate=True):
    pcol.get_query_sequences()

In [45]:
reads=col_list[-1]
flags=[pread.alignment.flag for pread in reads]
flags

[0,
 256,
 2048,
 0,
 256,
 2048,
 272,
 272,
 272,
 256,
 272,
 272,
 0,
 272,
 256,
 272,
 272,
 272,
 272,
 272,
 272,
 2064,
 272,
 256,
 256,
 256,
 272,
 272,
 256,
 272,
 272,
 272,
 272,
 256,
 256,
 256,
 272,
 272,
 2048,
 2064,
 0,
 272,
 0,
 272,
 16,
 0,
 272,
 272,
 256,
 272,
 272,
 272,
 272,
 16,
 256,
 256,
 256,
 272,
 272,
 256,
 272,
 272,
 272,
 272,
 272,
 0,
 272,
 2064,
 272,
 256,
 272,
 256,
 272,
 272,
 256,
 272,
 272,
 272,
 272,
 272,
 256,
 272,
 272,
 272,
 256,
 272,
 256,
 256,
 272,
 272,
 272,
 256,
 256,
 256,
 272,
 272,
 256,
 256,
 272,
 256,
 272,
 272,
 272,
 256,
 272,
 272,
 256,
 272,
 272,
 272,
 272,
 272,
 272,
 272,
 256,
 272,
 256,
 256,
 256,
 272,
 272,
 256,
 256,
 272,
 256,
 256,
 256,
 256,
 256,
 256,
 256,
 256,
 256,
 256,
 256,
 272,
 272,
 272,
 272,
 272,
 16,
 256,
 256,
 272,
 272,
 16,
 272,
 256,
 272,
 0,
 16,
 256,
 272,
 256,
 272,
 272,
 272,
 272,
 272,
 0,
 272,
 272,
 256,
 256,
 272,
 256,
 272,
 272,
 256,
 27

In [74]:
v_pos=27522077
for pcol in samfile.pileup('chr20',v_pos-3000000,v_pos+3000000,min_base_quality=0,flag_filter=0x4|0x100|0x200|0x400|0x800,truncate=True):
    pcol.get_query_sequences()

In [62]:
reads2=col_list2[-1]
flags2=[pread.alignment.flag for pread in reads2]
flags2

[0, 0, 0, 0, 0, 16, 0, 16, 0, 16, 16, 0, 16, 0, 16, 0]

In [75]:
pcol.get_query_sequences()

ValueError: PileupColumn accessed after iterator finished

In [66]:
len(flags2)

16

In [34]:
0x800 &0x100

0

In [55]:
pcol

In [56]:
pcol.pileups

ValueError: PileupColumn accessed after iterator finished

In [43]:
np.random.seed(10)
X=np.array([[1,2],[3,4],[5,6],[7,8]])
y=np.array([[11,22],[33,44],[55,66],[77,88]])

In [41]:
np.random.shuffle(x)
x

array([[5, 6],
       [1, 2],
       [7, 8],
       [3, 4]])

In [62]:
np.random.seed(10)
perm=np.random.permutation(len(X))

In [63]:
perm=np.random.permutation(len(X))
np.take(X,perm,axis=0,out=X)

array([[5, 6],
       [1, 2],
       [7, 8],
       [3, 4]])

In [69]:
y=np.array([[11,22],[33,44],[55,66],[77,88]])
y=np.take(y,perm,axis=0)
y

array([[55, 66],
       [11, 22],
       [77, 88],
       [33, 44]])

In [71]:
max(1,4)

4

In [66]:
s+'l%d' %9

'adsfgl9'

In [67]:
np.vstack([X,y])

array([[ 5,  6],
       [ 1,  2],
       [ 7,  8],
       [ 3,  4],
       [55, 66],
       [11, 22],
       [77, 88],
       [33, 44]])